### PR TITLE
Fixe on OCV3: could not be parsed as it uses an unsupported built-in tag

### PR DESCRIPTION
**Pull request by azahraoui**
A syntax error was detected in plugins/flynsarmy/sociallogin/updates/version.yaml. The string "!!! Important update with breaking changes." could not be parsed as it uses an unsupported built-in tag

### CODE REVIEW

**Comment by Flynsarmy** [comment]
Will this change break the warning update on October 1?

**Comment by Schtil** [comment]
This change should fix the issue with the syntax rules in the new October release.
The warning itself will remain

**Comment by Flynsarmy** [comment]
Thanks!

**Comment by Schtil** [comment]
Could you update the plugin https://octobercms.com/plugin/flynsarmy-sociallogin according to the changes?

**Pull request merged**
